---
layout: cv
title: Yuhsin Lin's CV
---
# Yuhsin Lin

<div id="emailaddress">
<a href="mailto:lin21022@byui.edu">lin21022@byui.edu</a>
| <a href="www.linkedin.com/in/yuhsin-lin-237580235">My Linkedin page</a>

</div>


## Currently

Mechanical Engineering student at Brigham Young University- Idaho.

### Techanical Skills:

- **Engineering & Design Tools:** SolidWorks (CSWA, CSWA-SD, CSWA-S), Finite Element Analysis (FEA), Revit, Thermal Design, and 3D printing. 

- **Programming & Data Analysis:** Python, Machine Learning, R, MySQL, and Mathematica. 

- **Microcontroller Systems:** Arduino, PID Control Systems, and Micro:bit. 

- **Professional:** Analytical thinking, data-driven decision making, and cross-functional team collaboration.



### Projects:

- **Mechatronics:** Arduino-based PID temperature control system.

- **Thermal Systems:** HVAC ventilation design/thermal load analysis. 

- **Mechanical Design:** Hands-free access assistants. 
 

## Education

```September 2022 - April 2027 (Anticipated)```  

**Brigham Young University - Idaho**, Rexburg, ID 

- Bachelor’s Degree in Mechanical Engineering 

- Minor in Data Science 

- GPA: 4.0/4.0

- Member of Tau Beta Pi National Engineering Society



## Certifications

- Certified SolidWorks Associate (CSWA) 

- SolidWorks Associate Sustainability (CSWA-SD) 

- SolidWorks Simulation Associate (CSWA-S)



## Work Experience
 
```September 2022 - Present``` 

**Teacher Assistant/Tutor**, Brigham Young University - Idaho 

- Supported diverse students learning 5+ STEM courses, including mechatronic systems, engineering statistics, physics, and chemistry.

- Collaborated with professors on grading, assignment design, and review sessions.

- Developed strong mentoring and communication skills to convey complex academic concepts.

```April 2023 - August 2023``` 

**Assembler Intern**, Polaris 

- Performed wide variety of tasks including preparing vehicle parts, sub-systems, and components.

- Improved product line efficiency through proactive problem solving and teamwork.

- Inspected approximately 80 vehicles per day on a moving assembly line with a nearly 100% defect-free quality rate.

```August 2021 - December 2021``` 

**Teacher Assistant**, Kumon 

- Trained 50 students in Math, English, and Chinese.

- Acquired leadership and interpersonal skills by organizing classes and cooperating with staff.

## Volunteer Experience

```September 2023 - February 2025``` 

**Full-time Volunteer Missionary**, The Church of Jesus Christ of Latter-Day Saints 

- Dedicated 18 months to community service and outreach in Ontario, Canada.

- Selected as a leader of 20+ representatives, providing training, coordination, and motivational support.

- Mentored 100+ individuals weekly, strengthening cross-cultural communication skills in native Chinese and professional English.

<!-- ### Footer

Last updated: May 2013 -->